services:
  - type: worker
    name: telegram-quiz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OCR_SPACE_API_KEY
        sync: false
      - key: LANG
        value: ar
