services:
  - type: worker
    name: telegram-quiz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "7761296155:AAFhJXXxLc5WxOWw5VN0Q82JrzywgFiI4_Q"
      - key: API_KEY
        value: "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"
      - key: LANG
        value: ar